import React from 'react';
import { 
  Home, 
  Compass, 
  Plus, 
  Newspaper, 
  UserCircle, 
  Sun, 
  Moon,
  MapPin,
  Calendar,
  Euro,
  ArrowRight,
  LogOut,
  Bell,
  Settings,
  Search,
  Sparkles,
  Music,
  Mic,
  Trophy,
  PartyPopper,
  BookOpen,
  ChevronLeft,
  ShieldCheck,
  Globe,
  Heart,
  Ticket,
  LayoutDashboard,
  Wand2,
  Brain,
  TrendingUp,
  Users,
  Activity,
  Coins,
  ChevronDown,
  MessageSquare,
  Send,
  X,
  CreditCard,
  CheckCircle2,
  Trash2,
  ShieldAlert,
  Star,
  List,
  Camera,
  ShieldPlus,
  UserX,
  ChevronRight,
  Lock,
  Check,
  Clock,
  AlertTriangle,
  Mail,
  Map as MapIcon,
  Navigation
} from 'lucide-react';

interface IconProps {
  size?: number;
  className?: string;
}

export const Icons = {
  Home: ({size=20, className=""}: IconProps) => <Home size={size} strokeWidth={2} className={className} />,
  Explore: ({size=20, className=""}: IconProps) => <Compass size={size} strokeWidth={2} className={className} />,
  Create: ({size=20, className=""}: IconProps) => <Plus size={size} strokeWidth={2} className={className} />,
  News: ({size=20, className=""}: IconProps) => <Newspaper size={size} strokeWidth={2} className={className} />,
  User: ({size=20, className=""}: IconProps) => <UserCircle size={size} strokeWidth={2} className={className} />,
  Sun: ({size=20, className=""}: IconProps) => <Sun size={size} strokeWidth={2} className={className} />,
  Moon: ({size=20, className=""}: IconProps) => <Moon size={size} strokeWidth={2} className={className} />,
  MapPin: ({size=14, className=""}: IconProps) => <MapPin size={size} strokeWidth={2} className={className} />,
  Calendar: ({size=14, className=""}: IconProps) => <Calendar size={size} strokeWidth={2} className={className} />,
  Euro: ({size=14, className=""}: IconProps) => <Euro size={size} strokeWidth={2} className={className} />,
  ArrowRight: ({size=14, className=""}: IconProps) => <ArrowRight size={size} strokeWidth={2.5} className={className} />,
  LogOut: ({size=20, className=""}: IconProps) => <LogOut size={size} strokeWidth={2} className={className} />,
  Bell: ({size=20, className=""}: IconProps) => <Bell size={size} strokeWidth={2} className={className} />,
  Settings: ({size=20, className=""}: IconProps) => <Settings size={size} strokeWidth={2} className={className} />,
  Search: ({size=20, className=""}: IconProps) => <Search size={size} strokeWidth={2} className={className} />,
  Sparkles: ({size=20, className=""}: IconProps) => <Sparkles size={size} strokeWidth={2} className={className} />,
  Music: ({size=24, className=""}: IconProps) => <Music size={size} strokeWidth={2} className={className} />,
  Mic: ({size=24, className=""}: IconProps) => <Mic size={size} strokeWidth={2} className={className} />,
  Trophy: ({size=24, className=""}: IconProps) => <Trophy size={size} strokeWidth={2} className={className} />,
  PartyPopper: ({size=24, className=""}: IconProps) => <PartyPopper size={size} strokeWidth={2} className={className} />,
  BookOpen: ({size=24, className=""}: IconProps) => <BookOpen size={size} strokeWidth={2} className={className} />,
  ChevronLeft: ({size=20, className=""}: IconProps) => <ChevronLeft size={size} strokeWidth={2} className={className} />,
  Shield: ({size=14, className=""}: IconProps) => <ShieldCheck size={size} strokeWidth={2} className={className} />,
  Ticket: ({size=20, className=""}: IconProps) => <Ticket size={size} strokeWidth={2} className={className} />,
  Dashboard: ({size=20, className=""}: IconProps) => <LayoutDashboard size={size} strokeWidth={2} className={className} />,
  Wand: ({size=14, className=""}: IconProps) => <Wand2 size={size} strokeWidth={2} className={className} />,
  Brain: ({size=14, className=""}: IconProps) => <Brain size={size} strokeWidth={2} className={className} />,
  TrendingUp: ({size=20, className=""}: IconProps) => <TrendingUp size={size} strokeWidth={2} className={className} />,
  Users: ({size=20, className=""}: IconProps) => <Users size={size} strokeWidth={2} className={className} />,
  Activity: ({size=20, className=""}: IconProps) => <Activity size={size} strokeWidth={2} className={className} />,
  Coins: ({size=20, className=""}: IconProps) => <Coins size={size} strokeWidth={2} className={className} />,
  ChevronDown: ({size=16, className=""}: IconProps) => <ChevronDown size={size} strokeWidth={2} className={className} />,
  MessageSquare: ({size=20, className=""}: IconProps) => <MessageSquare size={size} strokeWidth={2} className={className} />,
  Send: ({size=20, className=""}: IconProps) => <Send size={size} strokeWidth={2} className={className} />,
  X: ({size=20, className=""}: IconProps) => <X size={size} strokeWidth={2} className={className} />,
  CreditCard: ({size=20, className=""}: IconProps) => <CreditCard size={size} strokeWidth={2} className={className} />,
  Lock: ({size=14, className=""}: IconProps) => <Lock size={size} strokeWidth={2} className={className} />,
  CheckCircle: ({size=24, className=""}: IconProps) => <CheckCircle2 size={size} strokeWidth={2} className={className} />,
  Trash2: ({size=20, className=""}: IconProps) => <Trash2 size={size} strokeWidth={2} className={className} />,
  ShieldAlert: ({size=20, className=""}: IconProps) => <ShieldAlert size={size} strokeWidth={2} className={className} />,
  Star: ({size=20, className=""}: IconProps) => <Star size={size} strokeWidth={2} className={className} />,
  List: ({size=20, className=""}: IconProps) => <List size={size} strokeWidth={2} className={className} />,
  Camera: ({size=20, className=""}: IconProps) => <Camera size={size} strokeWidth={2} className={className} />,
  ShieldPlus: ({size=20, className=""}: IconProps) => <ShieldPlus size={size} strokeWidth={2} className={className} />,
  UserX: ({size=20, className=""}: IconProps) => <UserX size={size} strokeWidth={2} className={className} />,
  ChevronRight: ({size=20, className=""}: IconProps) => <ChevronRight size={size} strokeWidth={2} className={className} />,
  Check: ({size=20, className=""}: IconProps) => <Check size={size} strokeWidth={2} className={className} />,
  Clock: ({size=20, className=""}: IconProps) => <Clock size={size} strokeWidth={2} className={className} />,
  AlertTriangle: ({size=20, className=""}: IconProps) => <AlertTriangle size={size} strokeWidth={2} className={className} />,
  Trash: ({size=20, className=""}: IconProps) => <Trash2 size={size} strokeWidth={2} className={className} />,
  Mail: ({size=20, className=""}: IconProps) => <Mail size={size} strokeWidth={2} className={className} />,
  Globe: ({size=20, className=""}: IconProps) => <Globe size={size} strokeWidth={2} className={className} />,
  Heart: ({size=20, className=""}: IconProps) => <Heart size={size} strokeWidth={2} className={className} />,
  Map: ({size=20, className=""}: IconProps) => <MapIcon size={size} strokeWidth={2} className={className} />,
  Navigation: ({size=20, className=""}: IconProps) => <Navigation size={size} strokeWidth={2} className={className} />,
};
